spring:
  jpa:
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ENC(F5TOEub9PnypC/VoE2Wx6cFrsNfF+HpoAYrysyhSupObxMk3BzpHpHx4GozkZiUDEKa8srMymKo=)
    username: ENC(atRZ7CtUw38RLXSvYVwlJf7r1cnWQzN2)
    password: ENC(g0uZnfA5zhzXT5OOJS14Dvw==)
    driver-class-name: org.postgresql.Driver
  banner:
    location: banner.txt

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      order-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true
    default:  
      registerHealthIndicator: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: tlaxcala

jwt:
  secret: aEIu9S7cvZUnPJWezau3rKUCxj4BLtpCVzhVSyam93prJOxofs7688P0OD5tmTIsLL6u7G9HpXvT
