server:
  port: 8081
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: tlaxcala
spring:
  jpa:
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: mediapp
  datasource:
    password: ENC(gxN0JMThL2ypgO8wsuMD3Q==)
    driver-class-name: org.postgresql.Driver
    username: ENC(AYdCc65yTG1177SVBBGUivvgc+3GZq+v)
    url: ENC(W6FqanvTkTdUxE0oU5AFbWFJ3eskuDsAzLAJEE4x7tkPW1zWoJP8+pjnsLivrnyDTv26C6vJbE0=)
  banner:
    location: banner.txt
jwt:
  secret: ENC(dcZaXeVKl+yckUCC4qWKumXAOaYBynID/S2slHesMdtP87ZtZyl7dYfPlKgafTpsGgwRoY5MMGnZ10XmjSPKg6Eoz2/VRde1vOUYFn4zBQAWYSeKDXvStA==)
