server:
  port: 8090
  
spring:
  info:
    app:
      name: mediapp-consult
    description: Aplicacion de citas medicas
    version: 1.0.0
  application:
    name: mediapp-consult

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
