server:
  port: 8099

spring:
  application:
    name: mediapp-security

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
